### ISSUE TITLE
Patches

### ISSUE THREAD

**Issue by Tolriq** [jkj8790/LogJerry#2]
Sorry, don't have much time to do proper PRs except for the Json one.

You can find some stuff at https://github.com/Tolriq/LogJerry/tree/custom with quick add support for Zip files (My own use case of 1 zip 1 log file) and the update to compose 1.2 that for me fixes crashes when filtering by keyword. The rest is quick hacks to work on all OS, quick inverted tag filtering and a custom parser for my need, not really directly usable.

**Comment by jkj8790** [comment]
Thanks! I [check-picked some commits](https://github.com/jkj8790/LogJerry/pull/3) from your repo except the inverted tag and custom parser.
For inverted filtering, I have a plan to support it more conveniently way so I exclude it.
