### ISSUE TITLE
Support tag exclusion

### ISSUE THREAD

**Issue by Tolriq** [jkj8790/LogJerry#26]
Nice to see this is still alive.

Anyway to have tag exclusion? So the opposite of current tag filter.

**Comment by jkj8790** [comment]
Thanks for the suggestion! I think it's not difficult from implementation perspective but it's hard to think proper UI to acheive it... Anyway I'll try to add it in the next release!

**Comment by Tolriq** [comment]
I have it in my fork, I've added a new NoTag filter type. The rest is easy. Could be just labelled "Tag is not" below the tag one.
