### ISSUE TITLE
Support large row collapse.

### ISSUE THREAD

**Issue by Tolriq** [jkj8790/LogJerry#27]
Would be nice to have a proper way to support auto collapse of rows with very large texts.

I often have very large json or texts like (1Mb), having rows by default limited to a configurable number of lines that you can expand would hugely help.

I had a very quick hack in my fork: https://github.com/Tolriq/LogJerry/commit/13dd359450bd041723e54540f484faac32414596 but instead of rebasing all if the project is active would be nice to have this official.

**Comment by jkj8790** [comment]
Thanks for the suggestion! I'll try to update it later 🙇‍♂️

**Comment by jkj8790** [comment]
Actually I removed json collapse feature because I thought it wasn't useful but it was!!

**Comment by jkj8790** [comment]
Thanks for the idea! I made the the line count that determines whether a json should be collapsed configurable (5 was small to me 😅 I set the default as 20)
